# -*- coding: utf-8 -*-
"""O'zNLP Architecture.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12sN6JJ687YMG0OF6M_Jt3MyeoGhu83Ry
"""

# Sample raw text simulating messy scraped content
raw_scraped_text = "   O'zbekiston   Respublikasi   Prezidenti   matbuot   xizmati... \n\n   "

# 1. Strip trailing and leading whitespace
trimmed = raw_scraped_text.strip()

# 2. Split by any whitespace and rejoin to normalize irregular spaces
normalized_words = trimmed.split()
clean_text = " ".join(normalized_words)

print("Original:", repr(raw_scraped_text))
print("Cleaned: ", repr(clean_text))

# Mapping inconsistent quote marks to a single standardized apostrophe
char_replacement_map = {
    "‘": "'",
    "’": "'",
    "`": "'",
    "ʻ": "'",
    "ʼ": "'",
}

sample_sentence = "Oʻzbekiston va Qoraqalpog`iston o‘rtasidagi do‘stlik aloqalari."

normalized_sentence = sample_sentence
for bad_char, clean_char in char_replacement_map.items():
    normalized_sentence = normalized_sentence.replace(bad_char, clean_char)

print("Before:", sample_sentence)
print("After: ", normalized_sentence)

import requests

# 1. Define the target URL
url = "https://daryo.uz/"

# 2. Set a User-Agent header so the website does not block the script
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
}

# 3. Send the GET request to the website
response = requests.get(url, headers=headers)

# 4. Check if the request was successful
print(f"Status Code: {response.status_code}")

# 5. Print the first 500 characters of the raw HTML
print(response.text[:500])

from bs4 import BeautifulSoup

# 1. Parse the raw HTML text we got from Day 3
soup = BeautifulSoup(response.text, 'html.parser')

# 2. Find all paragraph tags (<p>) in the HTML document
paragraphs = soup.find_all('p')

# 3. Loop through every paragraph and print just the clean text
for p in paragraphs:
    clean_text = p.get_text(strip=True)
    if clean_text:  # This skips empty paragraphs
        print(clean_text)

import requests
from bs4 import BeautifulSoup
import time

# 1. Create a Python list containing multiple URLs
urls_to_scrape = [
    "https://daryo.uz/",
    "https://kun.uz/",
    "https://gazeta.uz/oz/"
]

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
}

# 2. Start the loop to visit each URL one by one
for current_url in urls_to_scrape:
    print(f"Connecting to: {current_url}")

    # Send the request
    response = requests.get(current_url, headers=headers)

    # Check if successful
    if response.status_code == 200:
        soup = BeautifulSoup(response.text, 'html.parser')
        paragraphs = soup.find_all('p')

        # Extract and print just the first 3 paragraphs to keep output clean
        for p in paragraphs[:3]:
            clean_text = p.get_text(strip=True)
            if clean_text:
                print(clean_text)
    else:
        print(f"Failed to connect. Status: {response.status_code}")

    print("--------------------------------------------------")

    # 3. Pause the script for 2 seconds before the next loop
    time.sleep(2)

import requests
from bs4 import BeautifulSoup
import time
import json  # Import the JSON module

urls_to_scrape = [
    "https://daryo.uz/",
    "https://kun.uz/",
    "https://gazeta.uz/oz/"
]

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
}

# 1. Create an empty list to hold all the scraped data
dataset = []

for current_url in urls_to_scrape:
    print(f"Scraping: {current_url}")
    response = requests.get(current_url, headers=headers)

    if response.status_code == 200:
        soup = BeautifulSoup(response.text, 'html.parser')
        paragraphs = soup.find_all('p')

        # Combine the paragraphs into one single block of text
        article_text = ""
        for p in paragraphs[:3]:
            clean_text = p.get_text(strip=True)
            if clean_text:
                article_text += clean_text + " "

        # 2. Add the URL and text into our list as a dictionary
        dataset.append({
            "source": current_url,
            "text": article_text.strip()
        })

    time.sleep(2)

# 3. Create a new file and write the data into it
with open("uzbek_nlp_data.json", "w", encoding="utf-8") as json_file:
    json.dump(dataset, json_file, ensure_ascii=False, indent=4)

print("Scraping complete. Data saved to uzbek_nlp_data.json!")

complex_mapping = {
    "ё": "yo", "Ё": "Yo",
    "ч": "ch", "Ч": "Ch",
    "ш": "sh", "Ш": "Sh",
    "ю": "yu", "Ю": "Yu",
    "я": "ya", "Я": "Ya",
    "ў": "o'", "Ў": "O'",
    "ғ": "g'", "Ғ": "G'"
}

simple_mapping = {
    "а": "a", "б": "b", "в": "v", "г": "g", "д": "d",
    "е": "e", "ж": "j", "з": "z", "и": "i", "й": "y",
    "к": "k", "л": "l", "м": "m", "н": "n", "о": "o",
    "п": "p", "р": "r", "с": "s", "т": "t", "у": "u",
    "ф": "f", "х": "x", "ц": "s", "э": "e", "қ": "q",
    "ҳ": "h"
}

def transliterate_to_latin(text):
    if not isinstance(text, str):
        return text

    for cyrillic, latin in complex_mapping.items():
        text = text.replace(cyrillic, latin)

    for cyrillic, latin in simple_mapping.items():
        text = text.replace(cyrillic, latin)

    return text

# Test it on a sample sentence:
test_sentence = "Ўзбекистон Республикаси – келажаги буюк давлат."
print("Converted:", transliterate_to_latin(test_sentence))

import pandas as pd

# 1. Load the JSON file you scraped on Day 6
df = pd.read_json("uzbek_nlp_data.json")

# 2. Run the transliteration function on the whole 'text' column
df["normalized_text"] = df["text"].apply(transliterate_to_latin)

# 3. View the first 2 rows to verify the transformation
print(df[["text", "normalized_text"]].head(2))

# 4. Save the normalized data to a clean CSV
df.to_csv("cleaned_uzbek_data.csv", index=False, encoding="utf-8")
print("Saved clean data to cleaned_uzbek_data.csv!")

# 1. Install the required Hugging Face libraries if you haven't yet
!pip install transformers datasets

import pandas as pd
from transformers import AutoTokenizer

# 2. Load the pre-trained tokenizer for XLM-RoBERTa
# We use xlm-roberta-base because it's lightweight enough for Colab's free GPU
model_checkpoint = "xlm-roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

# 3. Load your clean dataset from Week 2
df = pd.read_csv("cleaned_uzbek_data.csv")

# 4. Test the tokenizer on the first sentence of your dataset
sample_text = df["normalized_text"].iloc[0]
print("Original Text:", sample_text)

# Tokenize it!
tokenized_output = tokenizer(sample_text)

print("\nNumerical IDs (What the AI sees):")
print(tokenized_output["input_ids"])

# Convert the numbers back to tokens to see how it split the words
print("\nWord Breakdown (Tokens):")
print(tokenizer.convert_ids_to_tokens(tokenized_output["input_ids"]))

import random
from datasets import Dataset

# 1. Generate a random label (0 or 1) for every row in your dataset
df["label"] = [random.choice([0, 1]) for _ in range(len(df))]

# 2. Re-convert the updated Pandas table back into a Hugging Face dataset
hf_dataset = Dataset.from_pandas(df)

# 3. Re-tokenize the dataset so it includes the new "label" column
tokenized_dataset = hf_dataset.map(tokenize_function, batched=True)

# 4. Print the columns to verify "label" is now present alongside input_ids
print("New dataset features:", tokenized_dataset.features.keys())

import pandas as pd
import random
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer

# 1. Reload the Tokenizer and Foundation Model
model_checkpoint = "xlm-roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(model_checkpoint, num_labels=2)

# 2. Recreate a quick dummy dataset (assuming you have a 'cleaned_uzbek_data.csv' or similar text list)
# If you don't have the CSV loaded, we will make a tiny 2-sentence dataset just to make the code run
dummy_data = pd.DataFrame({
    "text": ["O'zbekiston iqtisodiyoti o'smoqda.", "Bugun havo juda issiq."],
    "label": [1, 0]
})
hf_dataset = Dataset.from_pandas(dummy_data)

def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True, max_length=128)

tokenized_dataset = hf_dataset.map(tokenize_function, batched=True)

# 3. Rebuild the Trainer
training_args = TrainingArguments(
    output_dir="./uzbek_nlp_model",
    num_train_epochs=1, # Just 1 epoch to make it fast for testing
    per_device_train_batch_size=2,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
)

# 4. Train and immediately save
print("Retraining model...")
trainer.train()

print("Saving model...")
trainer.save_model("./uzbek_nlp_model")
tokenizer.save_pretrained("./uzbek_nlp_model")
print("Saved successfully! You can now run the inference pipeline.")

!pip install gradio

import gradio as gr
from transformers import pipeline

# Load the fine-tuned physics classifier you saved earlier
classifier = pipeline("text-classification", model="./uzbek_nlp_model", tokenizer="./uzbek_nlp_model")

# Define the prediction logic for the website
def analyze_physics_problem(text):
    prediction = classifier(text)[0]
    label = prediction['label']
    confidence = round(prediction['score'] * 100, 1)

    # Assuming label 1 represents a verified physics problem
    if label == 1 or label == "1":
        return f"✅ Fizika masalasi (Confidence: {confidence}%)"
    else:
        return f"❌ Boshqa matn (Confidence: {confidence}%)"

# Design the website UI
interface = gr.Interface(
    fn=analyze_physics_problem,
    inputs=gr.Textbox(lines=5, placeholder="Masalaning matnini kiriting (Enter problem text here)..."),
    outputs="text",
    title="Uzbek Physics AI Classifier",
    description="Ushbu sun'iy intellekt matnning fizika masalasi ekanligini aniqlaydi."
)

# Launch the web app
interface.launch(share=True)

import pandas as pd

# 1. Create a dictionary containing real physics problems and random non-physics text
data = {
    "text": [
        # --- PHYSICS PROBLEMS (Label 1) ---
        "Bir xil manfiy zaryadga ega bo'lgan ikki metall sharcha 8 cm masofada 14,4 mkN kuch bilan o'zaro ta'sirlashmoqda. Har bir sharchada qancha ortiqcha elektron bo'lgan?", #
        "Ikkita bir xil sharcha bir-biridan 10 cm masofada turibdi. Ular bir xil miqdorda manfiy zaryadga ega bo'lib, 0,23 mN kuch bilan o'zaro ta'sirlashadi.", #
        "Uchta bir xil o'lchamli metall sharchaning biri +20 mkC, ikkinchisi -8 mkC, uchinchisi zaryadsiz. Sharchalar bir-biriga tekkizilib, avvalgi vaziyatiga qaytarildi.", #
        "Avtomobil tekis tezlanuvchan harakat qilib, o'z tezligini 10 s ichida 15 m/s dan 25 m/s gacha oshirdi. Uning tezlanishini toping.",

        # --- NON-PHYSICS TEXT (Label 0) ---
        "O'zbekiston Respublikasi Prezidenti matbuot xizmati xabar berishicha, yangi iqtisodiy islohotlar qabul qilindi.",
        "Bugun Toshkent shahrida havo harorati kechagiga nisbatan ancha issiq bo'lishi kutilmoqda.",
        "O'zbek tilining izohli lug'ati yangi so'zlar bilan boyitildi va nashrga tayyorlandi.",
        "Joriy yilda qishloq xo'jaligi sohasida paxta hosildorligini oshirish bo'yicha chora-tadbirlar ishlab chiqildi."
    ],
    "label": [1, 1, 1, 1, 0, 0, 0, 0]
}

# 2. Convert to a Pandas DataFrame
df_real = pd.DataFrame(data)

# 3. Save it as a CSV file to your Colab environment
df_real.to_csv("uzbek_physics_dataset.csv", index=False)

print("Dataset created successfully! Here is a preview:")
print(df_real.head(8))

import pandas as pd
from datasets import Dataset
from transformers import TrainingArguments, Trainer

# 1. Load the real physics dataset you just created
df_real = pd.read_csv("uzbek_physics_dataset.csv")
hf_real_dataset = Dataset.from_pandas(df_real)

# 2. Tokenize the text using your existing function
tokenized_real_dataset = hf_real_dataset.map(tokenize_function, batched=True)

# 3. Configure training for actual learning (3 epochs instead of 1)
training_args = TrainingArguments(
    output_dir="./uzbek_physics_model",
    num_train_epochs=3,
    per_device_train_batch_size=2,
    learning_rate=2e-5,
    weight_decay=0.01,
)

# 4. Assemble the Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_real_dataset,
)

# 5. Execute training
print("Training on real physics dataset...")
trainer.train()

# 6. Save the production weights
trainer.save_model("./uzbek_physics_model")
tokenizer.save_pretrained("./uzbek_physics_model")
print("Physics model saved successfully!")

classifier = pipeline("text-classification", model="./uzbek_physics_model", tokenizer="./uzbek_physics_model")

import pandas as pd

data = {
    "text": [
        "Bir xil manfiy zaryadga ega bo'lgan ikki metall sharcha 8 cm masofada 14,4 mkN kuch bilan o'zaro ta'sirlashmoqda. Har bir sharchada qancha ortiqcha elektron bo'lgan?",
        "Ikkita bir xil sharcha bir-biridan 10 cm masofada turibdi. Ular bir xil miqdorda manfiy zaryadga ega bo'lib, 0,23 mN kuch bilan o'zaro ta'sirlashadi.",
        "Uchta bir xil o'lchamli metall sharchaning biri +20 mkC, ikkinchisi -8 mkC, uchinchisi zaryadsiz. Sharchalar bir-biriga tekkizilib, avvalgi vaziyatiga qaytarildi.",
        "Avtomobil tekis tezlanuvchan harakat qilib, o'z tezligini 10 s ichida 15 m/s dan 25 m/s gacha oshirdi. Uning tezlanishini toping.",
        "O'zbekiston Respublikasi Prezidenti matbuot xizmati xabar berishicha, yangi iqtisodiy islohotlar qabul qilindi.",
        "Bugun Toshkent shahrida havo harorati kechagiga nisbatan ancha issiq bo'lishi kutilmoqda.",
        "O'zbek tilining izohli lug'ati yangi so'zlar bilan boyitildi va nashrga tayyorlandi.",
        "Joriy yilda qishloq xo'jaligi sohasida paxta hosildorligini oshirish bo'yicha chora-tadbirlar ishlab chiqildi."
    ],
    "label": [1, 1, 1, 1, 0, 0, 0, 0]
}

df_real = pd.DataFrame(data)
df_real.to_csv("uzbek_physics_dataset.csv", index=False)
print("Dataset created!")

from google.colab import files
files.download("uzbek_physics_dataset.csv")